INSERT INTO species_aliases (category, canonical_name, alias) VALUES
('fish', '광어', '광어'),
('fish', '황금광어', '황금광어'),
('fish', '광어', '제주광어'),
('fish', '참돔', '참돔'),
('fish', '참돔', '자연산참돔'),
('fish', '참돔', '도미'),
('fish', '감성돔', '감성돔'),
('fish', '돌도다리', '돌도다리'),
('fish', '돌도다리', '도다리'),
('fish', '돌도다리', '가자미'),
('fish', '능성어', '능성어'),
('fish', '농어', '농어'),
('fish', '자바리', '자바리'),
('fish', '점성어', '점성어'),
('fish', '시마아지', '시마아지'),
('fish', '시마아지', '흑점줄전갱이'),
('fish', '줄돔', '줄돔'),
('fish', '돌돔', '돌돔'),
('fish', '잿방어', '잿방어'),
('fish', '부시리', '부시리'),
('salmon', '연어', '연어'),
('shellfish', '전복', '전복'),
('shellfish', '가리비', '가리비'),
('shellfish', '가리비', '홍가리비'),
('shellfish', '가리비', '일산가리비'),
('shellfish', '참소라', '참소라'),
('shellfish', '새조개', '새조개'),
('shellfish', '쭈꾸미', '쭈꾸미'),
('crustacean', '킹크랩', '킹크랩'),
('crustacean', '킹크랩', '블루 킹크랩'),
('crustacean', '킹크랩', '레드 킹크랩'),
('crustacean', '대게', '대게'),
('crustacean', '대게', '마가단 대게');
