UPDATE species_profiles
SET
  market_weight_note = CASE canonical_name
    WHEN '광어' THEN 'FishBase 기준 최대 공개 중량 9.1kg, 최대 전장 103cm(TL)입니다.'
    WHEN '참돔' THEN 'FishBase 기준 최대 공개 중량 9.7kg, 최대 표준체장 100cm(SL), 일반 전장 30cm(TL)입니다.'
    WHEN '감성돔' THEN 'FishBase 기준 최대 공개 중량 3.2kg, 최대 표준체장 50cm(SL)입니다.'
    WHEN '돌도다리' THEN 'FishBase에는 최대 표준체장 50cm(SL)로 기재되어 있고, IGFA 기록어는 3.48kg/62cm입니다.'
    WHEN '능성어' THEN 'FishBase 기준 최대 공개 중량 62.8kg, 최대 전장 155cm(TL)입니다.'
    WHEN '농어' THEN 'FishBase 기준 최대 공개 중량 8.7kg, 최대 전장 102cm(TL)입니다.'
    WHEN '자바리' THEN 'FishBase 기준 최대 공개 중량 33kg, 최대 전장 136cm(TL), 일반 전장 60cm(TL)입니다.'
    WHEN '점성어' THEN 'FishBase 기준 최대 공개 중량 45kg, 최대 전장 155cm(TL), 일반 전장 100cm(TL)입니다.'
    WHEN '시마아지' THEN 'FishBase 기준 최대 공개 중량 18.1kg, 최대 전장 122cm(TL), 일반 전장 40cm(TL)입니다.'
    WHEN '줄돔' THEN 'FishBase 기준 최대 공개 중량 12.1kg, 최대 전장 86cm(TL)입니다.'
    WHEN '돌돔' THEN 'FishBase 기준 최대 공개 중량 6.4kg, 최대 전장 80cm(TL)입니다.'
    WHEN '잿방어' THEN 'FishBase 기준 최대 공개 중량 80.6kg, 최대 전장 190cm(TL), 일반 전장 100cm(TL)입니다.'
    WHEN '부시리' THEN 'FishBase 기준 최대 공개 중량 96.8kg, 최대 전장 250cm(TL), 일반 전장 80cm(TL)입니다.'
    WHEN '연어' THEN 'FishBase 기준 최대 공개 중량 46.8kg, 최대 전장 150cm(TL), 일반 전장 38cm(TL)입니다.'
    WHEN '개숭어' THEN 'FishBase 기준 최대 공개 중량 5kg, 최대 전장 80cm(TL), 일반 전장 50cm(TL)입니다.'
    WHEN '도다리' THEN 'FishBase 기준 최대 공개 중량 1kg, 최대 표준체장 30cm(SL)입니다.'
    WHEN '도미' THEN 'FishBase 기준 최대 공개 중량 9.7kg, 최대 표준체장 100cm(SL), 일반 전장 30cm(TL)입니다.'
    WHEN '방어' THEN 'FishBase 기준 최대 공개 중량 40kg, 최대 전장 150cm(TL)입니다.'
    WHEN '뱅에돔' THEN 'FishBase 기준 최대 전장 50cm(TL)이고, 국내 낚시 어종 정보는 평균 0.7~1.2kg, 최대 약 3kg로 설명합니다.'
    WHEN '보리숭어' THEN 'FishBase 기준 최대 표준체장 100cm(SL), 일반 표준체장 50cm(SL)이고, Animal Diversity Web은 최대 중량 8kg로 설명합니다.'
    WHEN '복어' THEN '대표 참복 기준 FishBase 최대 전장 80cm(TL), 일반 전장 40cm(TL)이고, 국내 음식문화 자료는 최대 약 3kg로 설명합니다.'
    WHEN '붉바리' THEN 'FishBase 기준 최대 공개 중량 2.5kg, 최대 전장 58cm(TL), 일반 전장 30cm(TL)입니다.'
    WHEN '숭어' THEN 'FishBase 기준 최대 표준체장 100cm(SL), 일반 표준체장 50cm(SL)이고, Animal Diversity Web은 최대 중량 8kg로 설명합니다.'
    WHEN '우럭' THEN 'FishBase 기준 최대 공개 중량 3.1kg, 최대 전장 65cm(TL)입니다.'
    WHEN '참복' THEN 'FishBase 기준 최대 전장 80cm(TL), 일반 전장 40cm(TL)이고, 국내 음식문화 자료는 최대 약 3kg로 설명합니다.'
    ELSE market_weight_note
  END,
  info_sources = CASE canonical_name
    WHEN '광어' THEN '["https://fishbase.se/summary/Paralichthys-olivaceus.html","https://www.busan.go.kr/fisheries/frfishpoint05","https://en.wikipedia.org/wiki/Olive_flounder"]'
    WHEN '참돔' THEN '["https://fishbase.se/summary/Pagrus-major.html","https://en.wikipedia.org/wiki/Pagrus_major","https://slds2.tistory.com/2287"]'
    WHEN '감성돔' THEN '["https://fishbase.se/summary/Acanthopagrus-schlegelii.html","https://en.wikipedia.org/wiki/Acanthopagrus_schlegelii","https://slds2.tistory.com/2287"]'
    WHEN '돌도다리' THEN '["https://fishbase.se/summary/Kareius-bicoloratus.html","https://www.guinnessworldrecords.com/world-records/85385-heaviest-fish-caught-stone-flounder","https://en.wikipedia.org/wiki/Stone_flounder"]'
    WHEN '능성어' THEN '["https://fishbase.se/summary/Hyporthodus-septemfasciatus.html","https://en.wikipedia.org/wiki/Hyporthodus_septemfasciatus","https://slds2.tistory.com/2287"]'
    WHEN '농어' THEN '["https://fishbase.se/summary/Lateolabrax-japonicus.html","https://en.wikipedia.org/wiki/Japanese_sea_bass","https://slds2.tistory.com/2287"]'
    WHEN '자바리' THEN '["https://fishbase.se/summary/Epinephelus-bruneus.html","https://en.wikipedia.org/wiki/Epinephelus_bruneus","https://slds2.tistory.com/2287"]'
    WHEN '점성어' THEN '["https://fishbase.se/summary/Sciaenops-ocellatus.html","https://www.fws.gov/species/red-drum-sciaenops-ocellatus","https://animaldiversity.org/accounts/Sciaenops_ocellatus/"]'
    WHEN '시마아지' THEN '["https://fishbase.se/summary/Pseudocaranx-dentex.html","https://en.wikipedia.org/wiki/White_trevally","https://slds2.tistory.com/2287"]'
    WHEN '줄돔' THEN '["https://fishbase.se/summary/Oplegnathus-punctatus.html","https://en.wikipedia.org/wiki/Oplegnathus_punctatus","https://slds2.tistory.com/2287"]'
    WHEN '돌돔' THEN '["https://fishbase.se/summary/Oplegnathus-fasciatus.html","https://en.wikipedia.org/wiki/Barred_knifejaw","https://slds2.tistory.com/2287"]'
    WHEN '잿방어' THEN '["https://fishbase.se/summary/Seriola-dumerili.html","https://en.wikipedia.org/wiki/Greater_amberjack","https://slds2.tistory.com/2287"]'
    WHEN '부시리' THEN '["https://fishbase.se/summary/Seriola-lalandi.html","https://en.wikipedia.org/wiki/Yellowtail_amberjack","https://slds2.tistory.com/2287"]'
    WHEN '연어' THEN '["https://fishbase.se/summary/Salmo-salar.html","https://en.wikipedia.org/wiki/Atlantic_salmon","https://slds2.tistory.com/2287"]'
    WHEN '개숭어' THEN '["https://fishbase.se/summary/Chelon-haematocheilus.html","https://en.wikipedia.org/wiki/Chelon_haematocheilus","https://slds2.tistory.com/2287"]'
    WHEN '도다리' THEN '["https://fishbase.se/summary/Pleuronichthys-cornutus.html","https://en.wikipedia.org/wiki/Ridged-eye_flounder","https://slds2.tistory.com/2287"]'
    WHEN '도미' THEN '["https://fishbase.se/summary/Pagrus-major.html","https://en.wikipedia.org/wiki/Pagrus_major","https://slds2.tistory.com/2287"]'
    WHEN '방어' THEN '["https://fishbase.se/summary/Seriola-quinqueradiata.html","https://en.wikipedia.org/wiki/Japanese_amberjack","https://slds2.tistory.com/2287"]'
    WHEN '뱅에돔' THEN '["https://fishbase.se/summary/Girella-punctata.html","https://www.bfg-fishing.com/fish-species/sea-bream","https://commons.wikimedia.org/wiki/Category:Girella_punctata"]'
    WHEN '보리숭어' THEN '["https://fishbase.se/summary/Mugil-cephalus.html","https://animaldiversity.org/accounts/Mugil_cephalus/","https://en.wikipedia.org/wiki/Flathead_grey_mullet"]'
    WHEN '복어' THEN '["https://fishbase.se/summary/Takifugu-rubripes.html","https://v.daum.net/v/ZgzYnIDghV","https://en.wikipedia.org/wiki/Takifugu"]'
    WHEN '붉바리' THEN '["https://fishbase.se/summary/Epinephelus-akaara.html","https://en.wikipedia.org/wiki/Hong_Kong_grouper","https://slds2.tistory.com/2287"]'
    WHEN '숭어' THEN '["https://fishbase.se/summary/Mugil-cephalus.html","https://animaldiversity.org/accounts/Mugil_cephalus/","https://en.wikipedia.org/wiki/Flathead_grey_mullet"]'
    WHEN '우럭' THEN '["https://fishbase.se/summary/Sebastes-schlegelii.html","https://en.wikipedia.org/wiki/Sebastes_schlegelii","https://slds2.tistory.com/2287"]'
    WHEN '참복' THEN '["https://fishbase.se/summary/Takifugu-rubripes.html","https://v.daum.net/v/ZgzYnIDghV","https://en.wikipedia.org/wiki/Takifugu_rubripes"]'
    ELSE info_sources
  END,
  updated_at = CURRENT_TIMESTAMP
WHERE category IN ('fish', 'salmon');
